# Use Nginx base image
FROM nginx:alpine

# Copy built frontend assets
COPY ./frontend/dist /usr/share/nginx/html

# Copy Nginx config
COPY ./deploy/nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]