"""Add firstname and lastname fields to user model.

Revision ID: 0c48358b4cd8
Revises: 8c777debd0e2
Create Date: 2025-11-14 15:21:22.581199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c48358b4cd8'
down_revision: Union[str, Sequence[str], None] = '8c777debd0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
