"""Add firstname and lastname fields to user schema.

Revision ID: ac75c5f9343a
Revises: 0c48358b4cd8
Create Date: 2025-11-14 15:52:35.937657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac75c5f9343a'
down_revision: Union[str, Sequence[str], None] = '0c48358b4cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
